### ISSUE TITLE
Question on sending email attachments

### ISSUE THREAD

**Issue by kensoh** [tebelorg/TA.Mail#1]
raised on behalf of user

---

Just a quick question, because I'm stuck with sending emails through Tmail api. Smtp config works, emails are sent, however I can not attach files with &ATTACHMENT= 
I have tried every path I could imagine, using / and \, also changeing the root of the path, starting with "c:/" or just leaving the name of the file itself. Do you have any suggestion?

like "&ATTACHMENT=test3.txt", while test3.txt exists in the same folder as the automation file I'm running. I receive the emails, but without attachment.

**Comment by v-akos** [comment]
Thanks for starting the issue. Please feel free to ask for more info if you need!

**Comment by kensoh** [comment]
Hi Akos, I had a look - I assume that you are already using Option 1 which is sending using SMTP. The location of the attachment file I believe is the same directory as mailer.php and not the location of the TagUI automation script. Maybe that's why, TagUI when calling the Tmail API it can't attach files through the API. I think it was originally meant to attach files from the mail server where the mailer.php is hosted.

**Comment by kensoh** [comment]
Hi Akos, I had a look - I assume that you are already using Option 1 which is sending using SMTP. The location of the attachment file I believe is the same directory as mailer.php and not the location of the TagUI automation script.

Maybe that's why, TagUI when calling the Tmail API it can't attach files through the API. I think it was originally meant to attach files from the mail server where the mailer.php is hosted.

**Comment by v-akos** [comment]
Hi Ken,
Yes, I tried to attach a file from a local folder using the API, not from the folder of mailer.php.
So is there any option for my needs of sending attachments through the API?

**Comment by kensoh** [comment]
Hi Akos, nope there isn't a way to send the binary data from local to the API to be used as attachment. A possible workaround you may consider is setting up SFTP (with SSH keys so that no need to login manually) or something to automate the sending of attachment file to the mail server, after that, it should be able to be attached by specifying the file on server.

**Comment by v-akos** [comment]
Ok, I see. Thanks for the suggestion as a possible workaround, I'll give it a try.
